name: lista_asistencia_actualizado
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  crypto: ^3.0.2
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  external_path: ^1.0.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.1.7
  flutter_speed_dial: ^6.2.0
  http: ^1.0.0
  intl: ^0.18.1
  local_auth: ^2.1.6
  open_file: ^3.3.1
  path: ^1.8.3
  path_provider: ^2.0.12
  pdf: ^3.8.4
  permission_handler: ^10.2.0
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
